#include "bgfx_compute.sh"

BUFFER_RW(u_particle, vec2, 0);
BUFFER_RW(u_pixels, vec4, 1);

uniform vec4 u_numPoints;
uniform vec4 u_radius;
uniform vec4 u_resolution;

NUM_THREADS(16, 16, 1)
void main() {
  uint idx = gl_GlobalInvocationID.x;
  uint idy = gl_GlobalInvocationID.y;
  uint id = idy * u_resolution.x + idx;

  vec2 uv = gl_GlobalInvocationID.xy / u_resolution.xy;

  u_pixels[id] = vec4(uv.x,uv.y, 1.0, 1.0);

}
